CREATE TABLE tb_sales (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    amount DECIMAL(12,6), 
    date date, 
    deals int, 
    visited int, 
    seller_id int, 
    primary key (id)
);

CREATE TABLE tb_sellers (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255), 
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS tb_sales ADD CONSTRAINT fk_seller_id FOREIGN KEY (seller_id) REFERENCES tb_sellers;
